Flp 77 create query store
SkillsFundingAgency/das-funding-apprenticeship-earnings pull request #21
Opened 2022-11-10 16:15 UTC by MichaelYoung1981

2022-11-11 12:01 UTC, ruslanss commented on src/Infrastructure/SqlAzureIdentityAuthenticationDbConnectionInterceptor.cs
> +        }
is this logging temporary?

2022-11-11 12:01 UTC, ruslanss commented on src/Infrastructure/SqlAzureIdentityAuthenticationDbConnectionInterceptor.cs
> +        return await base.ConnectionOpeningAsync(connection, eventData, result, cancellationToken);
more logging. looks like someone was debugging deployment

2022-11-11 12:02 UTC, ruslanss commented on src/Infrastructure/SqlAzureIdentityTokenProvider.cs
> +
more logging

2022-11-11 12:02 UTC, ruslanss commented on src/InnerApi/SFA.DAS.Funding.ApprenticeshipEarnings.InnerApi.csproj
> +
is this needed?

2022-11-11 12:03 UTC, ruslanss requested changes
check comments

2022-11-16 13:08 UTC, ruslanss approved these changes

2022-12-05 16:40 UTC, tom-gough approved these changes

2022-12-05 16:43 UTC, merged